#!/usr/bin/env python3
"""
Download NIST X-Ray Mass Attenuation Coefficient tables and generate a Rust
static data file (nist_tables.rs) for embedding in the raddose3d binary.

Sources:
  Elements: https://physics.nist.gov/PhysRefData/XrayMassCoef/ElemTab/z{NN}.html
  Mixtures: https://physics.nist.gov/PhysRefData/XrayMassCoef/ComTab/{name}.html

Usage:
  python3 scripts/generate_nist_tables.py

Writes:
  crates/raddose3d/src/nist_tables.rs
"""

import re
import sys
import time
import urllib.request
import urllib.error
from pathlib import Path

ELEM_SYMBOLS = [
    None,  # 0-indexed padding
    "H",  "He", "Li", "Be", "B",  "C",  "N",  "O",  "F",  "Ne",  # 1-10
    "Na", "Mg", "Al", "Si", "P",  "S",  "Cl", "Ar", "K",  "Ca",  # 11-20
    "Sc", "Ti", "V",  "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn",  # 21-30
    "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y",  "Zr",  # 31-40
    "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn",  # 41-50
    "Sb", "Te", "I",  "Xe", "Cs", "Ba", "La", "Ce", "Pr", "Nd",  # 51-60
    "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb",  # 61-70
    "Lu", "Hf", "Ta", "W",  "Re", "Os", "Ir", "Pt", "Au", "Hg",  # 71-80
    "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Ac", "Th",  # 81-90
    "Pa", "U",                                                       # 91-92
]

MIXTURE_SLUGS = [
    "a150", "adipose", "air", "alanine", "b100", "bakelite", "blood",
    "bone", "brain", "breast", "c552", "calcium", "ceric", "cesium",
    "concrete", "concreteba", "eye", "fluoride", "fricke", "gadolinium",
    "gafchromic", "gallium", "glass", "kodak", "lithium", "lithiumflu",
    "lung", "magnesium", "mercuric", "muscle", "mylar", "nylonfilm",
    "ovary", "photoemul", "pmma", "polyethylene", "polystyrene", "polyvinyl",
    "pyrex", "teflon", "telluride", "temethane", "tepropane", "testis",
    "tissue", "tissue4", "vinyl", "water",
]

CELL_RE = re.compile(r"<TD>\s*([0-9]\.[0-9]+E[+-][0-9]+)\s*</TD>", re.IGNORECASE)


def fetch(url: str, retries: int = 3) -> str:
    headers = {"User-Agent": "Mozilla/5.0 (compatible; RADDOSE-3D data fetch)"}
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=30) as resp:
                return resp.read().decode("utf-8", errors="replace")
        except urllib.error.URLError as e:
            if attempt < retries - 1:
                time.sleep(2 ** attempt)
            else:
                raise RuntimeError(f"Failed to fetch {url}: {e}") from e


def parse_table(html: str) -> list[tuple[float, float]]:
    """Extract (energy_MeV, mu_rho_cm2_per_g) pairs from NIST HTML table."""
    values = [float(m.group(1)) for m in CELL_RE.finditer(html)]
    result = []
    i = 0
    while i + 2 < len(values):
        energy_mev = values[i]
        mu_rho = values[i + 1]
        result.append((energy_mev, mu_rho))
        i += 3
    return result


def rust_pairs(pairs: list[tuple[float, float]]) -> str:
    items = ", ".join(f"({e:E}_f64, {m:E}_f64)" for e, m in pairs)
    return f"&[{items}]"


def main():
    out_path = Path(__file__).parent.parent / "crates" / "raddose3d" / "src" / "nist_tables.rs"

    lines = [
        "// Auto-generated by scripts/generate_nist_tables.py",
        "// NIST X-Ray Mass Attenuation Coefficients",
        "// https://physics.nist.gov/PhysRefData/XrayMassCoef/",
        "// DO NOT EDIT MANUALLY — regenerate with: python3 scripts/generate_nist_tables.py",
        "",
        "/// (energy_MeV, mu_rho_cm2_per_g) tables for individual elements, indexed by Z-1.",
        "/// Element Z=1 (H) is index 0, Z=92 (U) is index 91.",
        "pub static ELEM_MU_RHO: &[&[(f64, f64)]] = &[",
    ]

    for z in range(1, 93):
        symbol = ELEM_SYMBOLS[z]
        url = f"https://physics.nist.gov/PhysRefData/XrayMassCoef/ElemTab/z{z:02d}.html"
        print(f"  Z={z:02d} {symbol:2s}  {url}", flush=True)
        html = fetch(url)
        pairs = parse_table(html)
        if not pairs:
            print(f"    WARNING: no data found for Z={z}", file=sys.stderr)
        lines.append(f"    // Z={z} {symbol}")
        lines.append(f"    {rust_pairs(pairs)},")
        time.sleep(0.1)

    lines += [
        "];",
        "",
        "/// (energy_MeV, mu_rho_cm2_per_g) tables for NIST ComTab compound mixtures.",
        "/// Indexed in parallel with MIXTURE_NAMES.",
        "pub static MIXTURE_MU_RHO: &[&[(f64, f64)]] = &[",
    ]

    for slug in MIXTURE_SLUGS:
        url = f"https://physics.nist.gov/PhysRefData/XrayMassCoef/ComTab/{slug}.html"
        print(f"  mixture {slug:20s}  {url}", flush=True)
        html = fetch(url)
        pairs = parse_table(html)
        if not pairs:
            print(f"    WARNING: no data found for {slug}", file=sys.stderr)
        lines.append(f"    // {slug}")
        lines.append(f"    {rust_pairs(pairs)},")
        time.sleep(0.1)

    lines += [
        "];",
        "",
        "/// Lowercase material names for MIXTURE_MU_RHO (same order).",
        "pub static MIXTURE_NAMES: &[&str] = &[",
    ]
    for slug in MIXTURE_SLUGS:
        lines.append(f'    "{slug}",')
    lines += ["];", ""]

    content = "\n".join(lines)
    out_path.write_text(content)
    print(f"\nWrote {out_path}")
    print(f"  {len(ELEM_SYMBOLS)-1} elements, {len(MIXTURE_SLUGS)} mixtures")


if __name__ == "__main__":
    main()
